name: Projects Bord Automatisation

on:
  project_card:
    types: [moved]
    
jobs:
  create-branch:
   # Check if TODO colum and Card with issue
     if: github.event.project_card.column_id == 8924318 && github.event.project_card.content_url != null
     runs-on: ubuntu-latest
     env: 
       issueUrl: ${{ github.event.project_card.content_url }}
     steps:
     # Use Github App Token insted of secrets.GITHUB_TOKEN to be able to trigger other actions
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.0.2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: "Create Branch"
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          script: |
            // Get sha from Master
            const mSha = await github.git.getRef({owner: context.repo.owner, repo: context.repo.repo, ref: "heads/master"})
            
            // Get Issue number form card
            const issueURL = process.env.issueUrl
            const slashNum = issueURL.lastIndexOf("/")
            const issueNum = issueURL.substr(slashNum + 1)
            
            // Get Issue infos
            const issue = (await github.issues.get({owner: context.repo.owner, repo: context.repo.repo, issue_number: issueNum})).data
            // build branch name
            const branchName = `i${issue.number}-${issue.title.toLocaleLowerCase().replace(RegExp("\\[.*\\] "), "").split(" ").join("-")}`
            const branchUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/tree/${branchName}`
            
            // Create branch
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/${branchName}`,
              sha: mSha.data.object.sha
            }).then(res => {
              // On Success Write Comment
              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNum,
                body: `Branch [${branchName}](${branchUrl}) created!`,
              });
            })
  create-pull-request:
   # Check if Review colum and Card with issue
    if: github.event.project_card.column_id == 8924332 && github.event.project_card.content_url != null
    runs-on: ubuntu-latest
    env:
       issueUrl: ${{ github.event.project_card.content_url }}
    steps:
     # Use Github App Token insted of secrets.GITHUB_TOKEN to be able to trigger other actions
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.0.2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
        
      - name: "Create Pull request"
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            // Get Issue number form card
            const issueURL = process.env.issueUrl
            const slashNum = issueURL.lastIndexOf("/")
            const issueNum = issueURL.substr(slashNum + 1)
            
            // Get Issue infos
            const issue = (await github.issues.get({owner: context.repo.owner, repo: context.repo.repo, issue_number: issueNum})).data
            // build branch name
            const branchName = `i${issue.number}-${issue.title.toLocaleLowerCase().replace(RegExp("\\[.*\\] "), "").split(" ").join("-")}`
            
            // Create PullRequest
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `${issue.title}`,
              body: `resolves #${issueNum}`,
              head: branchName,
              base: "master",
            })
